---
version: "2.1"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ddclient:/config
    restart: unless-stopped
networks:
  default:
    external:
      name: mymacvlan1
volumes:
  ddclient